### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by Pushplaybang** [Pushplaybang/swipeout#2]
## Scope

the swipe package needs some improvements to its UX.
### Tasks
- [ ] occassional stutter on close
-  [ ] tolerance in the touchStart / toucMove so that vertical scrolling isn't "wobbly"
- [ ] weirdness in the touchEnd, that if you scroll in the wrong direction and then let go, it should not trigger the end callback.
